# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit configuration
# See: https://docs.coderabbit.ai/configuration

reviews:
  path_filters:
    - "!.specify/**"

